// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsrN718Ku7QA23tKfe6BW12EguKXCWwQo',
    appId: '1:590501952272:web:8942bc6d2215917cb68395',
    messagingSenderId: '590501952272',
    projectId: 'android-project-00',
    authDomain: 'android-project-00.firebaseapp.com',
    storageBucket: 'android-project-00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACeQpu67PbOEfs8hLQjURIaybOrT9SaXE',
    appId: '1:590501952272:android:959256decf994a80b68395',
    messagingSenderId: '590501952272',
    projectId: 'android-project-00',
    storageBucket: 'android-project-00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6z1zicvf0UAMzrQGoJHEEA4qVWdMeVuA',
    appId: '1:590501952272:ios:93e01d6d1541f93db68395',
    messagingSenderId: '590501952272',
    projectId: 'android-project-00',
    storageBucket: 'android-project-00.appspot.com',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6z1zicvf0UAMzrQGoJHEEA4qVWdMeVuA',
    appId: '1:590501952272:ios:f18108766100463bb68395',
    messagingSenderId: '590501952272',
    projectId: 'android-project-00',
    storageBucket: 'android-project-00.appspot.com',
    iosBundleId: 'com.example.flutterApplication7.RunnerTests',
  );
}
